# 应用名称
spring:
  application:
    name: payment-demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_demo?serverTimezone=GMT%2B8&characterEncoding=utf-8
    password: 123wjh
    username: root
server:
  port: 8090

mybatis-plus:
  mapper-locations: classpath:com/wjh/payment/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql日志
